# Generated by Django 5.0.2 on 2025-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на услугу', 'verbose_name_plural': 'Заявки на услуги'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
