# Generated by Django 5.0.2 on 2025-05-19 16:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_app', '0002_alter_servicerequest_options_and_more'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailmedia', '0004_duration_optional_floatfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Вступительный текст для главной страницы')),
                ('video', models.ForeignKey(blank=True, help_text='Видео для герой-секции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
