# Generated by Django 5.0.2 on 2025-05-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_app', '0004_workphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Короткое описание страницы для поисковых систем (до 160 символов).', verbose_name='Мета-описание (SEO Description)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Список ключевых слов через запятую для поисковых систем.', max_length=255, verbose_name='Ключевые слова (SEO Keywords)'),
        ),
    ]
