# Generated by Django 5.0.2 on 2025-05-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_app', '0006_remove_homepage_seo_description_and_more'),
        ('wagtailmedia', '0004_duration_optional_floatfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_mobile',
            field=models.ForeignKey(blank=True, help_text='Мобильное видео для герой-секции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
