# Generated by Django 5.0.2 on 2025-06-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_app', '0007_homepage_video_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место назначения'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место забора'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Предпочтительное время'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='problem_details',
            field=models.TextField(blank=True, null=True, verbose_name='Детали проблемы'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(blank=True, choices=[('evacuation', 'Эвакуация'), ('roadside_assistance', 'Техпомощь на дороге'), ('towing', 'Буксировка'), ('tire_change', 'Замена колеса'), ('battery_jumpstart', 'Прикурить аккумулятор'), ('fuel_delivery', 'Доставка топлива'), ('lockout_service', 'Вскрытие замков'), ('other', 'Другое')], max_length=50, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='urgency',
            field=models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('emergency', 'Экстренная')], default='medium', max_length=20, verbose_name='Срочность'),
        ),
    ]
