# Generated by Django 5.0.2 on 2025-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_app', '0008_servicerequest_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='problem_details',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Time'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(blank=True, choices=[('towing', 'Буксировка'), ('battery_jumpstart', 'Прикурить аккумулятор'), ('fuel_delivery', 'Доставка топлива'), ('other', 'Другое')], max_length=50, null=True, verbose_name='Тип услуги'),
        ),
    ]
